### ISSUE TITLE
Error reported about missing resource

### ISSUE THREAD

**Issue by amitdev** [amitdev/PMD-Intellij#101]
This exception is seen some times, but there is no issues with functionality. Would be good to fix this though.

```
java.util.MissingResourceException: Can't find bundle for base name com.intellij.plugins.bodhi.pmd.PMD-Intellij, locale en_AU
	at java.base/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2055)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1689)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1593)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1556)
	at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:857)
	at com.intellij.plugins.bodhi.pmd.handlers.PMDCheckinHandler.message(PMDCheckinHandler.java:84)
	at com.intellij.plugins.bodhi.pmd.handlers.PMDCheckinHandler.getBeforeCheckinConfigurationPanel(PMDCheckinHandler.java:53)
	at com.intellij.vcs.commit.AbstractCommitWorkflowHandler.getBeforeOptions(AbstractCommitWorkflowHandler.kt:188)
	at com.intellij.vcs.commit.AbstractCommitWorkflowHandler.createCommitOptions(AbstractCommitWorkflowHandler.kt:93)
	at com.intellij.vcs.commit.NonModalCommitWorkflowHandler.ensureCommitOptions(NonModalCommitWorkflowHandler.kt:236)
	at com.intellij.vcs.commit.NonModalCommitWorkflowHandler.saveCommitOptions(NonModalCommitWorkflowHandler.kt:228)
	at com.intellij.vcs.commit.NonModalCommitWorkflowHandler.saveCommitOptions(NonModalCommitWorkflowHandler.kt:225)
	at com.intellij.vcs.commit.AbstractCommitWorkflowHandler.executeDefault(AbstractCommitWorkflowHandler.kt:121)
	at com.intellij.vcs.commit.AbstractCommitWorkflowHandler.access$executeDefault(AbstractCommitWorkflowHandler.kt:50)
	at com.intellij.vcs.commit.AbstractCommitWorkflowHandler$executorCalled$1.invoke(AbstractCommitWorkflowHandler.kt:108)
	at com.intellij.vcs.commit.AbstractCommitWorkflowHandler$executorCalled$1.invoke(AbstractCommitWorkflowHandler.kt:50)
	at com.intellij.vcs.commit.AbstractCommitWorkflow$startExecution$1.invoke(AbstractCommitWorkflow.kt:131)
	at com.intellij.vcs.commit.AbstractCommitWorkflow$startExecution$1.invoke(AbstractCommitWorkflow.kt:67)
	at com.intellij.vcs.commit.AbstractCommitWorkflow.continueExecution$intellij_platform_vcs_impl(AbstractCommitWorkflow.kt:138)
	at com.intellij.vcs.commit.AbstractCommitWorkflow.startExecution$intellij_platform_vcs_impl(AbstractCommitWorkflow.kt:129)
	at com.intellij.vcs.commit.AbstractCommitWorkflowHandler.executorCalled(AbstractCommitWorkflowHandler.kt:105)
	at com.intellij.vcs.commit.AbstractCommitWorkflowHandler.execute(AbstractCommitWorkflowHandler.kt:103)
	at com.intellij.openapi.vcs.changes.actions.BaseCommitExecutorAction.actionPerformed(BaseCommitExecutorAction.kt:32)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:240)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:261)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:240)
	at com.intellij.util.ui.JButtonAction$createCustomComponent$1.actionPerformed(JButtonAction.kt:27)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:270)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6652)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:887)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:816)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:753)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:442)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:494)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by cyanotyp** [comment]
In my IntelliJ IDEA 2021.2.1 (Ultimate Edition), Build #IU-212.5080.55, built on August 24, 2021, 
the Plugin crashes with this message, IntelliJ shows a bug report and the plugin stops working, I need it and don't want to disable it. Pls investigate and fix this topic.

**Comment by amitdev** [comment]
Interesting. I have the same version (IntelliJ IDEA 2021.2.1 Ultimate) but it keeps working. Anyway I'll take a look at this soon.

**Comment by Fengxq2014** [comment]
The same problem when I submit the code

**Comment by cyanotyp** [comment]
Thank you for your commitment and your commit, works for me :)
