### ISSUE TITLE
NullPointerException (NPE) when run on Java file with record

### ISSUE THREAD

**Issue by espertus** [amitdev/PMD-Intellij#137]
I am using IntelliJ IDEA 2022.3.3 (Ultimate Edition) and the latest version of your plugin (1.8.27). When I run PMD with all predefined rules and target SDK 17 I son my file `TestResult.java`, this exception is thrown:

```
Exception caught and swallowed: 

java.lang.NullPointerException: Cannot invoke "java.lang.Throwable.getMessage()" because the return value of "java.lang.Throwable.getCause()" is null
	at com.intellij.plugins.bodhi.pmd.core.PMDProcessingError.<init>(PMDProcessingError.java:21)
	at com.intellij.plugins.bodhi.pmd.core.PMDResultAsTreeRenderer.renderErrors(PMDResultAsTreeRenderer.java:76)
	at com.intellij.plugins.bodhi.pmd.core.PMDResultAsTreeRenderer.end(PMDResultAsTreeRenderer.java:92)
	at net.sourceforge.pmd.PmdAnalysis.finishRenderers(PmdAnalysis.java:279)
	at net.sourceforge.pmd.PmdAnalysis.performAnalysisAndCollectReport(PmdAnalysis.java:243)
	at net.sourceforge.pmd.PmdAnalysis.performAnalysis(PmdAnalysis.java:226)
	at com.intellij.plugins.bodhi.pmd.core.PMDResultCollector.runPMDAndGetResults(PMDResultCollector.java:85)
	at com.intellij.plugins.bodhi.pmd.PMDInvoker$1.run(PMDInvoker.java:175)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:281)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$9(CoreProgressManager.java:513)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:84)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
Here is the source code for the class:

```
package newgrader.crossgrader;

record TestResult(String testName, boolean passed,
                  String methodUnderTestName, String message) {
    private static final String SUCCESS_MESSAGE = "PASSED";

    static TestResult makeFailure(String testName, String methodUnderTestName, String message) {
        return new TestResult(testName, false, methodUnderTestName, message);
    }

    static TestResult makeSuccess(String testName, String methodUnderTestName) {
        return new TestResult(testName, true, methodUnderTestName, SUCCESS_MESSAGE);
    }
}
```

I suspect the error has to do with my code having `record`, which is a relatively new language feature (JDK 16). I am able to run PMD 7.0.0-RC2 from the command line on the file without error:
```
$ bin/bin/pmd check -d src/main/java/newgrader/crossgrader/TestResult.java -R rulesets/java/quickstart.xml -f text
[main] INFO net.sourceforge.pmd.cli.commands.internal.AbstractPmdSubcommand - Log level is at INFO
[main] WARN net.sourceforge.pmd.cli.commands.internal.PmdCommand - Progressbar rendering conflicts with reporting to STDOUT. No progressbar will be shown. Try running with argument -r <file> to output the report to a file instead.
[main] WARN net.sourceforge.pmd.cli.commands.internal.PmdCommand - This analysis could be faster, please consider using Incremental Analysis: https://docs.pmd-code.org/pmd-doc-7.0.0-rc2/pmd_userdocs_incremental_analysis.html
```

**Comment by jborgers** [comment]
Hi @espertus, thanks for your message. 
The NullPointerException should not be there, that is a bug. The processing error should be reported. I guess it is reported because the Java version for PMD used in the plugin is < 16. What is the version you have configured in the PMD Plugin? (IntelliJ Settings - PMD - Options - Target JDK)

**Comment by jborgers** [comment]
@espertus, I cannot reproduce your problem with that source code. If you run PMD in Intellij just on that source file, you get that NullPointerException? Where does it show?

**Comment by jborgers** [comment]
Thanks, that helps. It happens only when running the design rule set (or All). I was using our custom ruleset, jpinpoint-rules.

It seems to be a bug in pmd, we use 6.55 in the plugin. Did you test that version as commandline tool?

**Comment by jborgers** [comment]
And with JDK15 configured:
<img width="960" alt="image" src="https://github.com/amitdev/PMD-Intellij/assets/24591067/8bb2624b-a4ce-446b-a208-40dcd01869db">

**Comment by espertus** [comment]
In the plugin, I get the error when I run PMD with `category/java/design`, so that's what I tried just now at the command line:
```
ellen@DESKTOP-25TKO9O MINGW64 ~/Downloads/pmd-bin-6.55.0/pmd-bin-6.55.0/bin
$ ./pmd.bat -d TestResult.java -R rulesets/java/design.xml
```
I don't get that error, although I get a whole bunch of deprecation warnings. https://pastebin.com/1Nuhaekd

Are there other tests I should run at the command line? I've attached the result of this command line:
```
./pmd.bat --verbose -d TestResult.java -R rulesets/java/design.xml 2> verbose-output.txt
```
[verbose-output.txt](https://github.com/amitdev/PMD-Intellij/files/11547878/verbose-output.txt)

[PMD 6.55.0 supports through 20-preview](https://pmd.github.io/pmd/pmd_languages_java.html), so it should have no trouble with records, which were added in 16.

**Comment by jborgers** [comment]
Thanks. I think PMD as cmdline swallows the exception somehow. I files the bug with pmd 6.55 and since that is the last 6 version, they are not going to fix it. 
Maybe we should disable the StdCyclomaticComplexityRule but it still provides value for non-records so that may not be a good idea. 
I think it is best to just have it in the processing errors list, this is in my PR. Hopefully released soon.

**Comment by jborgers** [comment]
I made the fix available as pre-release: 1.8.28-snapshot, see:
https://github.com/jborgers/PMD-Intellij/releases

You can download and import this plugin from file in IntelliJ. Let me know your experience.

**Comment by espertus** [comment]
You are amazing! It's rare for companies to be so responsive to paid
customers. It's incredible for you to be so responsive to free customers.

**Comment by jborgers** [comment]
Thank you, you are welcome!

Does the snapshot version solve your issue?

**Comment by espertus** [comment]
Yes. It shows it as a processing error and reports the other violations.

Thank you!

![image](https://github.com/amitdev/PMD-Intellij/assets/661056/84aedf83-6344-4eee-a07e-e59656cc4dc2)

**Comment by jborgers** [comment]
Okay, great. And the tooltip shows more details.

Op vr 26 mei 2023 02:49 schreef Ellen Spertus ***@***.***>:
