### ISSUE TITLE
IDE Internal Errors. Record

### ISSUE THREAD

**Issue by AntonMenov** [amitdev/PMD-Intellij#142]
If I run PMD on such a record, an error occurs.

```
Exception caught and swallowed: 

java.lang.NullPointerException: Cannot invoke "java.lang.Throwable.getMessage()" because the return value of "java.lang.Throwable.getCause()" is null
	at com.intellij.plugins.bodhi.pmd.core.PMDProcessingError.<init>(PMDProcessingError.java:21)
	at com.intellij.plugins.bodhi.pmd.core.PMDResultAsTreeRenderer.renderErrors(PMDResultAsTreeRenderer.java:76)
	at com.intellij.plugins.bodhi.pmd.core.PMDResultAsTreeRenderer.end(PMDResultAsTreeRenderer.java:92)
	at net.sourceforge.pmd.PmdAnalysis.finishRenderers(PmdAnalysis.java:279)
	at net.sourceforge.pmd.PmdAnalysis.performAnalysisAndCollectReport(PmdAnalysis.java:243)
	at net.sourceforge.pmd.PmdAnalysis.performAnalysis(PmdAnalysis.java:226)
	at com.intellij.plugins.bodhi.pmd.core.PMDResultCollector.runPMDAndGetResults(PMDResultCollector.java:85)
	at com.intellij.plugins.bodhi.pmd.PMDInvoker$1.run(PMDInvoker.java:175)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:281)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$9(CoreProgressManager.java:513)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:84)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

![image](https://github.com/amitdev/PMD-Intellij/assets/20296415/8c3c7607-9a6f-4774-acb4-c290932b989c)

```java
public record Aasdas() {

    private static int inta = 0;

    public static int getId(final int dealId) {
        return inta;
    }

    public void setId(final int dealId) {
        inta = dealId;
    }

}
```

**Comment by jborgers** [comment]
Should be solved with my PR https://github.com/amitdev/PMD-Intellij/pull/140
Please try te pre-release: https://github.com/jborgers/PMD-Intellij/releases

**Comment by jborgers** [comment]
Right, that is as intended. Hovering over it will show more details of where the exception occured, so it can be addressed, e.g. submitted for the pmd tool, what I expect where it originates. I submitted such a bug with them already.
Unfortunately, they will not fix bugs in version 6.55 anymore, they focus on 7. 
Switching to 7 is not so easy since it is backwards incompatible.

**Comment by AntonMenov** [comment]
> @AntonMenov Does this work for you?

I think so. Used the same code as before.

![image](https://github.com/amitdev/PMD-Intellij/assets/20296415/f9fdf76b-c0ab-4f66-a84c-d609bd105a9b)

**Comment by jborgers** [comment]
Okay, good. See also #137
