### ISSUE TITLE
PMD plugin not working when scanning only part of the code

### ISSUE THREAD

**Issue by sushi2k** [amitdev/PMD-Intellij#21]
Hi,
I was creating a custom rule and added it to the PMD IntelliJ plugin and it is working. I was executing the custom rule on a full Java Project and the pattern was identified in IntelliJ. The pattern I am looking for is a dummy so doesn't make sense now, I just wanted to see how the creation of rules is working with XPath. 

![screenshot at feb 04 15-40-43](https://cloud.githubusercontent.com/assets/5951320/12808944/d4fe09a2-cb55-11e5-9402-9d4fb72e8ad5.png)

If I only scan this one Java file in another Instance of IntelliJ with the same custom rule the pattern cannot be identified. 

![screenshot at feb 04 15-41-22](https://cloud.githubusercontent.com/assets/5951320/12808943/d49bf690-cb55-11e5-8d3e-1c5839b1359c.png)

Sometimes I need to scan single Java files without actually having access to the full source. PDM would be quiet useful for this job as I can create custom rules. 

Is it possible to scan only one or a bunch of Java files without actually having the full source? If so, how can it be done and what am I doing wrong?

Thanks and cheers.

**Comment by sushi2k** [comment]
Just for completion, this is the rule I created and loaded into IntelliJ-PMD:

```
<?xml version="1.0"?>
<ruleset name="My custom rules" xmlns="http://pmd.sf.net/ruleset/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:schemaLocation="http://pmd.sf.net/ruleset/1.0.0 http://pmd.sf.net/ruleset_xml_schema.xsd" xsi:noNamespaceSchemaLocation="http://pmd.sf.net/ruleset_xml_schema.xsd">
    <rule name="WhileLoopsMustUseBracesRule" 
          message="Avoid using 'while' statements without curly braces"
          class="net.sourceforge.pmd.lang.rule.XPathRule"
          language="java">
      <description>
      Avoid using 'while' statements without using curly braces
      </description>
        <priority>3</priority>
      <properties>
      <property name="path">
          <value>
          <![CDATA[
              //Name[@Image='answer_statement.executeQuery']
          ]]>
          </value>
      </property>
      </properties>
      <example>
      <![CDATA[
          public void doSomething() {
            while (true)
                x++;
          }
      ]]>
      </example>
    </rule>
</ruleset>
```

**Comment by amitdev** [comment]
@sushi2k I'm a bit busy now, will take a look at this in few days.

**Comment by amitdev** [comment]
For me this is working (I tried on Idea 15.0.3). The custom ruleset is working both in a project as well as on single file opened without project. I had to change the ruleset you pasted above with:
`property  name="xpath"`

**Comment by sushi2k** [comment]
Thanks for your answer. I am also using version 15.0.3. I changed the property name to xpath, but somehow I do not get any result.
I just created an empty Java project and copied this one file into the src folder. Afterwards I was scanning with all the pre defined rules and I got 336 violations. 

![screenshot at feb 10 11-30-52](https://cloud.githubusercontent.com/assets/5951320/12938095/43f0f584-cfea-11e5-928d-10c96db4812c.png)

Afterwards I imported the following XML file:

```
<?xml version="1.0"?>
<ruleset name="My custom rules" xmlns="http://pmd.sf.net/ruleset/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:schemaLocation="http://pmd.sf.net/ruleset/1.0.0 http://pmd.sf.net/ruleset_xml_schema.xsd" xsi:noNamespaceSchemaLocation="http://pmd.sf.net/ruleset_xml_schema.xsd">
    <rule name="WhileLoopsMustUseBracesRule" 
          message="Avoid using 'while' statements without curly braces"
          class="net.sourceforge.pmd.lang.rule.XPathRule"
          language="java">
      <description>
      Avoid using 'while' statements without using curly braces
      </description>
        <priority>3</priority>
      <properties>
      <property name="xpath">
          <value>
          <![CDATA[
              //Name[@Image='answer_statement.executeQuery']
          ]]>
          </value>
      </property>
      </properties>
      <example>
      <![CDATA[
          public void doSomething() {
            while (true)
                x++;
          }
      ]]>
      </example>
    </rule>
</ruleset>
```

The file is imported successfully and I can select it in my custom rules. 

![screenshot at feb 10 11-35-52](https://cloud.githubusercontent.com/assets/5951320/12938112/7a9696de-cfea-11e5-93e4-4822df3c051c.png)

If I run the scan on this custom rule there is no finding. But also if I run the entire scan for the Pre defined rules again I get no result. It seems the scan is not running at all. Even if I close and start IntelliJ again or remove the custom rule the results for the pre defined rules are 0.

![screenshot at feb 10 11-37-39](https://cloud.githubusercontent.com/assets/5951320/12938139/b60ba452-cfea-11e5-9ba1-271f81bd5ba1.png)

**Comment by sushi2k** [comment]
I've just seen in the bottom left corner an error message, saying NullPointerException for the PMDPlugin. So I guess that is the reason for this behaviour. 

```
null
java.lang.NullPointerException
	at net.sourceforge.pmd.renderers.AbstractIncrementingRenderer.renderFileReport(AbstractIncrementingRenderer.java:58)
	at net.sourceforge.pmd.renderers.HTMLRenderer.renderBody(HTMLRenderer.java:62)
	at com.intellij.plugins.bodhi.pmd.PMDResultPanel$9.getReportText(PMDResultPanel.java:304)
	at com.intellij.ide.util.ExportToFileUtil$ExportDialogBase.initText(ExportToFileUtil.java:164)
	at com.intellij.ide.util.ExportToFileUtil$ExportDialogBase.<init>(ExportToFileUtil.java:154)
	at com.intellij.ide.actions.ExportToTextFileAction.export(ExportToTextFileAction.java:36)
	at com.intellij.ide.actions.ExportToTextFileAction.actionPerformed(ExportToTextFileAction.java:32)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:161)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:125)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:299)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)


```

![screenshot at feb 10 16-25-35](https://cloud.githubusercontent.com/assets/5951320/12942069/0e604342-d013-11e5-9e16-ff3f1a8ad0e9.png)

**Comment by amitdev** [comment]
Thanks for the detailed information. Does the project have all dependent libraries? I suspect it is because the file cannot be compiled.

**Comment by amitdev** [comment]
I've updated the plugin to show errors from PMD in the results. So if the issue was with PMD it should show that now instead of the exception. Please update the plugin and let me know.

**Comment by sushi2k** [comment]
Thanks. So this is the error message now:

![screenshot at feb 11 09-31-31](https://cloud.githubusercontent.com/assets/5951320/12967522/409010ce-d0a2-11e5-8330-b8719beb3424.png)

The thing is sometimes I need to have a look at only a few Java files without having access to all the dependent libraries or the whole project. So in that case the plugin is not working, is that correct? 
As PMD is using AST by going through the source I expected that the java files are not compiled and do not need all the dependencies.

**Comment by amitdev** [comment]
The error is returned by PMD, so I cannot do much. Did you try running PMD via command line on this file? If it works from command line I can look at PMD side to see why it is failing.

**Comment by sushi2k** [comment]
If I run it on command line on the full project I get a result. But if I only run it on this specific file I do not get any result. Also debug information does not give me any more hints. Just to understand PDM better: Is it possible by desing of PMD to scan single Java files even when dependencies are missing? Or do I need the full project in order to work with PMD?

![screenshot at feb 11 14-22-45](https://cloud.githubusercontent.com/assets/5951320/12970545/07c8fbd8-d0cb-11e5-8261-a20f581312a8.png)

**Comment by sushi2k** [comment]
By the way I was using PDM 5.4.1 on the command line, the latest version available.

**Comment by amitdev** [comment]
Can you run command line on the failed project with the single file? I guess that will fail too.

**Comment by sushi2k** [comment]
Sorry, didn't included it into my previous post. Yes, it also fails and is not detected in the other project.

**Comment by amitdev** [comment]
Maybe you can post this question to PMD mailing list or issues and check if this is "expected behavior".

**Comment by sushi2k** [comment]
Thanks for the hint. Will do that.

**Comment by sushi2k** [comment]
After making a pause for two weeks, I just fund the problem. The comment //NOPMD was in the line. So my fault. Thanks for your help.
