### ISSUE TITLE
Not able to add rulesets xml in PMD

### ISSUE THREAD

**Issue by satiagomunez** [amitdev/PMD-Intellij#34]

**Comment by satiagomunez** [comment]
<?xml version="1.0"?>
<ruleset name="Custom Ruleset"
    xmlns="http://pmd.sf.net/ruleset/1.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sf.net/ruleset/1.0.0 http://pmd.sf.net/ruleset_xml_schema.xsd"
    xsi:noNamespaceSchemaLocation="http://pmd.sf.net/ruleset_xml_schema.xsd">

           
    
    <rule ref="rulesets/basic.xml/EmptyCatchBlock">
        <priority>3</priority>
    </rule>
    <rule ref="rulesets/basic.xml/EmptyIfStmt">
        <priority>3</priority>
    </rule>
    <rule ref="rulesets/basic.xml/EmptyWhileStmt">
        <priority>3</priority>
    </rule>
    <rule ref="rulesets/basic.xml/EmptyTryBlock">
        <priority>3</priority>
    </rule>
    <rule ref="rulesets/basic.xml/EmptyFinallyBlock">
        <priority>3</priority>
    </rule>
    <rule ref="rulesets/basic.xml/EmptySwitchStatements">
        <priority>3</priority>
    </rule>
    <rule ref="rulesets/basic.xml/JumbledIncrementer">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/basic.xml/ForLoopShouldBeWhileLoop">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/basic.xml/UnnecessaryConversionTemporary">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/basic.xml/OverrideBothEqualsAndHashcode">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/basic.xml/DoubleCheckedLocking">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/basic.xml/ReturnFromFinallyBlock">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/basic.xml/EmptySynchronizedBlock">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/basic.xml/UnnecessaryReturn">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/basic.xml/EmptyStaticInitializer">
        <priority>3</priority>
    </rule>
    <rule ref="rulesets/basic.xml/UnconditionalIfStatement">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/basic.xml/EmptyStatementNotInLoop">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/basic.xml/BooleanInstantiation">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/basic.xml/UnnecessaryFinalModifier">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/basic.xml/CollapsibleIfStatements">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/basic.xml/UselessOverridingMethod">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/basic.xml/ClassCastExceptionWithToArray">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/basic.xml/AvoidDecimalLiteralsInBigDecimalConstructor">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/basic.xml/UselessOperationOnImmutable">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/basic.xml/MisplacedNullCheck">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/basic.xml/UnusedNullCheckInEquals">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/basic.xml/AvoidThreadGroup">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/basic.xml/BrokenNullCheck">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/basic.xml/BigIntegerInstantiation">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/basic.xml/AvoidUsingOctalValues">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/basic.xml/AvoidUsingHardCodedIP">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/basic.xml/CheckResultSet">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/basic.xml/AvoidMultipleUnaryOperators">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/basic.xml/EmptyInitializer">
        <priority>3</priority>
    </rule>
	<rule ref="rulesets/basic.xml/DontCallThreadRun">
        <priority>1</priority>
    </rule>
    
	   
    <rule ref="rulesets/optimizations.xml/AvoidInstantiatingObjectsInLoops">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/optimizations.xml/UseArrayListInsteadOfVector">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/optimizations.xml/SimplifyStartsWith">
        <priority>5</priority>
    </rule>    
    <rule ref="rulesets/optimizations.xml/UseArraysAsList">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/optimizations.xml/AvoidArrayLoops">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/optimizations.xml/UnnecessaryWrapperObjectCreation">
        <priority>3</priority>
    </rule>
    <rule ref="rulesets/optimizations.xml/AddEmptyString">
        <priority>3</priority>
    </rule>
	
	 
    <rule ref="rulesets/strings.xml/AvoidDuplicateLiterals">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/strings.xml/StringInstantiation">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/strings.xml/StringToString">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/strings.xml/InefficientStringBuffering">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/strings.xml/UnnecessaryCaseChange">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/strings.xml/UseStringBufferLength">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/strings.xml/AppendCharacterWithChar">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/strings.xml/ConsecutiveLiteralAppends">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/strings.xml/UseIndexOfChar">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/strings.xml/InefficientEmptyStringCheck">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/strings.xml/InsufficientStringBufferDeclaration">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/strings.xml/UselessStringValueOf">
        <priority>3</priority>
    </rule>
    <rule ref="rulesets/strings.xml/StringBufferInstantiationWithChar">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/strings.xml/UseEqualsToCompareStrings">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/strings.xml/AvoidStringBufferField">
        <priority>5</priority>
    </rule>
        
    
    <rule ref="rulesets/codesize.xml/NPathComplexity">
        <priority>1</priority>
    </rule>
    <rule ref="rulesets/codesize.xml/ExcessiveMethodLength">
        <priority>1</priority>
    </rule>
    <rule ref="rulesets/codesize.xml/ExcessiveParameterList">
        <priority>1</priority>
    </rule>
    <rule ref="rulesets/codesize.xml/ExcessiveClassLength">
        <priority>1</priority>
    </rule>
    <rule ref="rulesets/codesize.xml/CyclomaticComplexity">
        <priority>1</priority>
    </rule>
    <rule ref="rulesets/codesize.xml/ExcessivePublicCount">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/codesize.xml/TooManyFields">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/codesize.xml/NcssMethodCount">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/codesize.xml/NcssTypeCount">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/codesize.xml/NcssConstructorCount">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/codesize.xml/TooManyMethods">
        <priority>5</priority>
    </rule>    
        
    
    <rule ref="rulesets/coupling.xml/CouplingBetweenObjects">
        <priority>1</priority>
    </rule>
    <rule ref="rulesets/coupling.xml/ExcessiveImports">
        <priority>1</priority>
    </rule>
    <rule ref="rulesets/coupling.xml/LooseCoupling">
        <priority>1</priority>
    </rule>
	
	
    <rule ref="rulesets/imports.xml/DuplicateImports">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/imports.xml/DontImportJavaLang">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/imports.xml/UnusedImports">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/imports.xml/ImportFromSamePackage">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/imports.xml/TooManyStaticImports">
        <priority>5</priority>
    </rule>
	
	
    <rule ref="rulesets/finalizers.xml/EmptyFinalizer">
        <priority>3</priority>
    </rule>
    <rule ref="rulesets/finalizers.xml/FinalizeOnlyCallsSuperFinalize">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/finalizers.xml/FinalizeOverloaded">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/finalizers.xml/FinalizeDoesNotCallSuperFinalize">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/finalizers.xml/FinalizeShouldBeProtected">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/finalizers.xml/AvoidCallingFinalize">
        <priority>5</priority>
    </rule>
	
		
    <rule ref="rulesets/naming.xml/ShortMethodName">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/naming.xml/VariableNamingConventions">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/naming.xml/MethodNamingConventions">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/naming.xml/ClassNamingConventions">
        <priority>3</priority>
    </rule>
    <rule ref="rulesets/naming.xml/AbstractNaming">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/naming.xml/AvoidDollarSigns">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/naming.xml/MethodWithSameNameAsEnclosingClass">
        <priority>3</priority>
    </rule>
    <rule ref="rulesets/naming.xml/SuspiciousHashcodeMethodName">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/naming.xml/SuspiciousConstantFieldName">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/naming.xml/SuspiciousEqualsMethodName">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/naming.xml/AvoidFieldNameMatchingTypeName">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/naming.xml/AvoidFieldNameMatchingMethodName">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/naming.xml/NoPackage">
        <priority>3</priority>
    </rule>
    <rule ref="rulesets/naming.xml/PackageCase">
        <priority>3</priority>
    </rule>
    <rule ref="rulesets/naming.xml/MisleadingVariableName">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/naming.xml/BooleanGetMethodName">
        <priority>3</priority>
    </rule>
	<rule ref="rulesets/naming.xml/GenericsNaming">
        <priority>5</priority>
    </rule>
	
	    
    <rule ref="rulesets/typeresolution.xml/CloneMethodMustImplementCloneable">
        <priority>5</priority>
    </rule>
	<rule ref="rulesets/typeresolution.xml/SignatureDeclareThrowsException">
        <priority>5</priority>
    </rule>
    
    
    <rule ref="rulesets/unusedcode.xml/UnusedPrivateField">
        <priority>3</priority>
    </rule>
    <rule ref="rulesets/unusedcode.xml/UnusedLocalVariable">
        <priority>3</priority>
    </rule>
    <rule ref="rulesets/unusedcode.xml/UnusedPrivateMethod">
        <priority>3</priority>
    </rule>
    <rule ref="rulesets/unusedcode.xml/UnusedFormalParameter">
        <priority>1</priority>
    </rule>
    
    
    <rule ref="rulesets/design.xml/UseSingleton">
        <priority>1</priority>
    </rule>
    <rule ref="rulesets/design.xml/SimplifyBooleanReturns">
        <priority>3</priority>
    </rule>
    <rule ref="rulesets/design.xml/SimplifyBooleanExpressions">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/design.xml/SwitchStmtsShouldHaveDefault">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/design.xml/AvoidDeeplyNestedIfStmts">
        <priority>1</priority>
    </rule>
    <rule ref="rulesets/design.xml/AvoidReassigningParameters">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/design.xml/SwitchDensity">
        <priority>1</priority>
    </rule>
    <rule ref="rulesets/design.xml/ConstructorCallsOverridableMethod">
        <priority>1</priority>
    </rule>
    <rule ref="rulesets/design.xml/AccessorClassGeneration">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/design.xml/FinalFieldCouldBeStatic">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/design.xml/CloseResource">
        <properties>
            <property name="types" value="Connection,Statement,ResultSet,JMSConnection"/>  
            <property name="closeTargets" value="close()"/>  
        </properties>
        <priority>3</priority>
    </rule>
    <rule ref="rulesets/design.xml/NonStaticInitializer">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/design.xml/DefaultLabelNotLastInSwitchStmt">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/design.xml/NonCaseLabelInSwitchStatement">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/design.xml/OptimizableToArrayCall">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/design.xml/BadComparison">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/design.xml/EqualsNull">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/design.xml/ConfusingTernary">
        <priority>3</priority>
    </rule>
    <rule ref="rulesets/design.xml/InstantiationToGetClass">
        <priority>3</priority>
    </rule>
    <rule ref="rulesets/design.xml/IdempotentOperations">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/design.xml/SimpleDateFormatNeedsLocale">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/design.xml/ImmutableField">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/design.xml/UseLocaleWithCaseConversions">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/design.xml/AvoidProtectedFieldInFinalClass">
        <priority>3</priority>
    </rule>
    <rule ref="rulesets/design.xml/AssignmentToNonFinalStatic">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/design.xml/MissingStaticMethodInNonInstantiatableClass">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/design.xml/AvoidSynchronizedAtMethodLevel">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/design.xml/MissingBreakInSwitch">
        <priority>1</priority>
    </rule>
    <rule ref="rulesets/design.xml/UseNotifyAllInsteadOfNotify">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/design.xml/AvoidInstanceofChecksInCatchClause">
        <priority>3</priority>
    </rule>
    <rule ref="rulesets/design.xml/AbstractClassWithoutAbstractMethod">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/design.xml/SimplifyConditional">
        <priority>3</priority>
    </rule>
    <rule ref="rulesets/design.xml/CompareObjectsWithEquals">
        <priority>3</priority>
    </rule>
    <rule ref="rulesets/design.xml/PositionLiteralsFirstInComparisons">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/design.xml/UnnecessaryLocalBeforeReturn">
        <priority>3</priority>
    </rule>
    <rule ref="rulesets/design.xml/NonThreadSafeSingleton">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/design.xml/UncommentedEmptyMethod">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/design.xml/UncommentedEmptyConstructor">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/design.xml/AvoidConstantsInterface">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/design.xml/UnsynchronizedStaticDateFormatter">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/design.xml/PreserveStackTrace">
        <priority>1</priority>
    </rule>
    <rule ref="rulesets/design.xml/UseCollectionIsEmpty">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/design.xml/ClassWithOnlyPrivateConstructorsShouldBeFinal">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/design.xml/EmptyMethodInAbstractClassShouldBeAbstract">
        <priority>3</priority>
    </rule>
    <rule ref="rulesets/design.xml/SingularField">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/design.xml/ReturnEmptyArrayRatherThanNull">
        <priority>3</priority>
    </rule>
    <rule ref="rulesets/design.xml/AbstractClassWithoutAnyMethod">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/design.xml/TooFewBranchesForASwitchStatement">
        <priority>3</priority>
    </rule>

        
    
    <rule ref="rulesets/strictexception.xml/AvoidCatchingThrowable">
        <priority>3</priority>
    </rule>
    <rule ref="rulesets/strictexception.xml/SignatureDeclareThrowsException">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/strictexception.xml/ExceptionAsFlowControl">
        <priority>3</priority>
    </rule>
    <rule ref="rulesets/strictexception.xml/AvoidCatchingNPE">
        <priority>3</priority>
    </rule>
    <rule ref="rulesets/strictexception.xml/AvoidThrowingRawExceptionTypes">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/strictexception.xml/AvoidThrowingNullPointerException">
        <priority>3</priority>
    </rule>
    <rule ref="rulesets/strictexception.xml/AvoidRethrowingException">
        <priority>3</priority>
    </rule>
    <rule ref="rulesets/strictexception.xml/DoNotExtendJavaLangError">
        <priority>5</priority>
    </rule>
    <rule ref="rulesets/strictexception.xml/DoNotThrowExceptionInFinally">
        <priority>3</priority>
    </rule>
    <rule ref="rulesets/strictexception.xml/AvoidThrowingNewInstanceOfSameException">
        <priority>3</priority>
    </rule>
	<rule ref="rulesets/strictexception.xml/AvoidCatchingGenericException">
        <priority>5</priority>
    </rule>
	<rule ref="rulesets/strictexception.xml/AvoidLosingExceptionInformation">
        <priority>5</priority>
    </rule>
    
   
    
    
    <rule ref="rulesets/sunsecure.xml/MethodReturnsInternalArray">
        <priority>3</priority>
    </rule>
    <rule ref="rulesets/sunsecure.xml/ArrayIsStoredDirectly">
        <priority>5</priority>
    </rule>
    
    
    
    
    <rule ref="rulesets/nc_rules.xml/Check setting AttributeValue">        
        <priority>5</priority>
    </rule>
    
    <rule ref="rulesets/nc_rules.xml/Check using ReferenceResolver.resolveID(id)">
        <priority>3</priority>
    </rule>
    
    <rule ref="rulesets/nc_rules.xml/Check using findById() for NCObjectHome">
        <priority>3</priority>
    </rule>
    
    <rule ref="rulesets/nc_rules.xml/Check using JDBC Framework instead of plain JDBC">
        <priority>3</priority>
    </rule>
    
    <rule ref="rulesets/nc_rules.xml/Check using of JDBCTemplates">
        <priority>3</priority>
    </rule>
    
    <rule ref="rulesets/nc_rules.xml/Check using UserTransaction">
        <priority>3</priority>
    </rule>
    
    <rule ref="rulesets/nc_rules.xml/Check using transactions in WebService">
        <priority>3</priority>
    </rule>
    
    <rule ref="rulesets/nc_rules.xml/Check using logger in a catch statement">
        <priority>3</priority>
    </rule>
    
    <rule ref="rulesets/nc_rules.xml/Check using empty collections">
        <priority>3</priority>
    </rule>
    
    <rule ref="rulesets/nc_rules.xml/Check bind variables">
        <priority>3</priority>
    </rule>
    
    <rule ref="rulesets/nc_rules.xml/Check replacement in sql">
        <priority>3</priority>
    </rule>
    
    <rule ref="rulesets/nc_rules.xml/Check using collection with single element">
        <priority>3</priority>
    </rule>
    
    <rule ref="rulesets/nc_rules.xml/Check using read only collection with more than one element">
        <priority>3</priority>
    </rule>
        
</ruleset>

**Comment by satiagomunez** [comment]
Logs : 

net.sourceforge.pmd.RuleSetFactory.createRuleSet(Ljava/lang/String;)Lnet/sourceforge/pmd/RuleSet;
java.lang.NoSuchMethodError: net.sourceforge.pmd.RuleSetFactory.createRuleSet(Ljava/lang/String;)Lnet/sourceforge/pmd/RuleSet;
	at com.intellij.plugins.bodhi.pmd.core.PMDResultCollector.isValidRuleSet(PMDResultCollector.java:132)
	at com.intellij.plugins.bodhi.pmd.PMDConfigurationForm.modifyRuleSet(PMDConfigurationForm.java:141)
	at com.intellij.plugins.bodhi.pmd.PMDConfigurationForm.access$300(PMDConfigurationForm.java:31)
	at com.intellij.plugins.bodhi.pmd.PMDConfigurationForm$AddRuleSetAction.actionPerformed(PMDConfigurationForm.java:172)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:197)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:156)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:211)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:188)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:154)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:325)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.i(IdeEventQueue.java:793)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:625)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:778)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:455)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1665)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1607)
	at com.intellij.openapi.options.newEditor.SettingsDialog.access$101(SettingsDialog.java:41)
	at com.intellij.openapi.options.newEditor.SettingsDialog.a(SettingsDialog.java:77)
	at com.intellij.openapi.project.DumbPermissionServiceImpl.allowStartingDumbModeInside(DumbPermissionServiceImpl.java:37)
	at com.intellij.openapi.project.DumbService.allowStartingDumbModeInside(DumbService.java:283)
	at com.intellij.openapi.options.newEditor.SettingsDialog.show(SettingsDialog.java:77)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:94)
	at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:62)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:197)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:156)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:211)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.a(ActionMenuItem.java:304)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:905)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:284)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.a(ActionMenuItem.java:112)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:40)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:113)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:123)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:109)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:112)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:513)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:45)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:533)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.i(IdeEventQueue.java:793)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:625)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by amitdev** [comment]
What is the plugin version? Are you using the latest one?

**Comment by satiagomunez** [comment]
Version 1.8.1
A plugin to run static analysis using PMD in intelliJ.
Change Notes
Support for PMD 5.5.1. This needs java version 1.7+.
Vendor
bodhi

**Comment by amitdev** [comment]
Can you check your ruleset? In PMD 5.5.1 there are some differences in rule location - https://pmd.github.io/pmd-5.5.1/pmd-java/rules/index.html. For example, the `EmptyIfStmnt` is in `empty.xml`.

**Comment by amitdev** [comment]
Assume this is no longer an issue.
