### ISSUE TITLE
PMD Plugin throwing exception (PMD 6.12 / Plugin 1.8.9)

### ISSUE THREAD

**Issue by JeroenSfdc** [amitdev/PMD-Intellij#67]
I'm unable to use the PMD Plugin in IntelliJ. 
I have used it successfully in the past.
Reporting same error as another user (Plugin review page). 

java.lang.NoClassDefFoundError: org/antlr/runtime/TokenSource
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:306)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:302)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:271)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:182)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:136)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:49)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:306)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:302)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:271)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:182)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:136)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:49)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.sourceforge.pmd.lang.apex.ApexJorjeLogging.disableLogging(ApexJorjeLogging.java:22)
	at net.sourceforge.pmd.lang.apex.ast.ApexParser.<init>(ApexParser.java:33)
	at net.sourceforge.pmd.lang.apex.ApexParser.<init>(ApexParser.java:24)
	at net.sourceforge.pmd.lang.apex.ApexHandler.getParser(ApexHandler.java:59)
	at net.sourceforge.pmd.PMD.parserFor(PMD.java:172)
	at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:173)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:96)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:51)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:78)
	at net.sourceforge.pmd.processor.MonoThreadProcessor.runAnalysis(MonoThreadProcessor.java:29)
	at net.sourceforge.pmd.processor.AbstractPMDProcessor.processFiles(AbstractPMDProcessor.java:108)
	at net.sourceforge.pmd.PMD.processFiles(PMD.java:329)
	at com.intellij.plugins.bodhi.pmd.core.PMDResultCollector.generateReport(PMDResultCollector.java:109)
	at com.intellij.plugins.bodhi.pmd.core.PMDResultCollector.getResults(PMDResultCollector.java:72)
	at com.intellij.plugins.bodhi.pmd.PMDInvoker$1.run(PMDInvoker.java:172)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:248)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:731)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$10(ApplicationImpl.java:594)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.antlr.runtime.TokenSource PluginClassLoader[PMDPlugin, 1.8.9] com.intellij.ide.plugins.cl.PluginClassLoader@7ba4f64f
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:51)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 50 more

**Comment by amitdev** [comment]
I've updated the plugin. Can you please try now?

**Comment by tlgabrantes** [comment]
Hi,

Thank you very much for the update.

I've already tested it and it is working fine.

Thank you very much for you work.

Regards,
Tiago.

**Comment by tlgabrantes** [comment]
Awesome, thanks!

**Comment by JeroenSfdc** [comment]
Hi @amitdev - great work, many thanks. Confirmed-fixed! :top:
